***Install the libraries***

In [1]:
!pip install gTTS
!pip install nltk

In [2]:
from gtts import gTTS
import IPython.display as ipd

In [3]:

# Text you want to convert to speech
text = "Hello class 5th Bridging Department of Math, welcome to the Text to Speech project !"
# Create an audio file
tts = gTTS(text)
tts.save("output.mp3")

# Play the audio in the notebook
ipd.Audio("output.mp3")


In [4]:
# Example text in Urdu
text_urdu = "آپ کا دن خوشگوار گزرے"
# Example text in Arabic
text_arabic = "السلام عليكم"

# Convert to speech
tts_urdu = gTTS(text_urdu, lang='ur')
tts_arabic = gTTS(text_arabic, lang='ar')

# Save the audio files
tts_urdu.save("urdu_speech.mp3")
tts_arabic.save("arabic_speech.mp3")

# Play the audio in Colab
print("Urdu Speech:")
ipd.display(ipd.Audio("urdu_speech.mp3"))

print("Arabic Speech:")
ipd.display(ipd.Audio("arabic_speech.mp3"))


Urdu Speech:


Arabic Speech:


NLP projects

In [13]:
import nltk
from nltk.tokenize import word_tokenize


# Download NLTK data (only needed once)
nltk.download('punkt')

# Updated predefined lists of words for emotions
happy_words = ["happy", "joy", "love", "excited", "great", "fantastic", "wonderful", "joyful"]
sad_words = ["sad", "upset", "unhappy", "bad", "depressed", "terrible", "crying", "miserable"]


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [6]:
def analyze_sentiment(text):
    tokens = word_tokenize(text.lower())
    happy_count = sum([1 for word in tokens if word in happy_words])
    sad_count = sum([1 for word in tokens if word in sad_words])

    if happy_count > sad_count:
        return "Happy 😊"
    elif sad_count > happy_count:
        return "Sad 😢"
    else:
        return "Neutral 😐"



In [14]:
# Example text
text_1 = "I am feeling very joyful and excited about the day!"
text_2 = "I'm so sad and miserable, it's been a crying day."

# Analyze sentiment
print(analyze_sentiment(text_1))  # Output: Happy 😊
print(analyze_sentiment(text_2))  # Output: Sad 😢


Happy 😊
Sad 😢


***Make Vacuum Cleaner Agent***

**Implement the Vacuum Cleaner Agent**: Below is the code to create a simple vacuum cleaner agent that can navigate a 2D grid, cleaning dirty spots.

In [16]:
import numpy as np

class VacuumCleanerAgent:
    def __init__(self, room):
        self.room = room  # Room represented as a 2D array (0: clean, 1: dirty)
        self.position = (0, 0)  # Starting position (0,0)
        self.cleaned_spots = 0  # Count of cleaned spots

    def is_dirty(self, position):
        """Check if the current position is dirty."""
        return self.room[position] == 1

    def clean(self):
        """Clean the current position."""
        if self.is_dirty(self.position):
            self.room[self.position] = 0  # Clean the spot
            self.cleaned_spots += 1
            print(f"Cleaned spot at {self.position}. Total cleaned: {self.cleaned_spots}")

    def move(self, direction):
        """Move the vacuum cleaner in the specified direction."""
        x, y = self.position
        if direction == 'up' and x > 0:
            self.position = (x - 1, y)
        elif direction == 'down' and x < self.room.shape[0] - 1:
            self.position = (x + 1, y)
        elif direction == 'left' and y > 0:
            self.position = (x, y - 1)
        elif direction == 'right' and y < self.room.shape[1] - 1:
            self.position = (x, y + 1)
        else:
            print("Move not possible!")

    def operate(self):
        """Perform cleaning until the room is clean."""
        while True:
            self.clean()  # Clean the current spot

            # Check for dirty spots around the current position
            if self.is_dirty(self.position):
                continue  # If still dirty, stay and clean

            # Move to the next available position
            moved = False
            for direction in ['down', 'right', 'up', 'left']:  # Order of preference
                x, y = self.position
                if direction == 'down' and x < self.room.shape[0] - 1:
                    self.move(direction)
                    moved = True
                    break
                elif direction == 'right' and y < self.room.shape[1] - 1:
                    self.move(direction)
                    moved = True
                    break
                elif direction == 'up' and x > 0:
                    self.move(direction)
                    moved = True
                    break
                elif direction == 'left' and y > 0:
                    self.move(direction)
                    moved = True
                    break

            # If no move was possible and no dirty spot was found
            if not moved:
                print("No more dirty spots found!")
                break

# Example Usage
# Creating a room with dirty spots (1 for dirty, 0 for clean)
room = np.array([[0, 1, 0],
                 [1, 1, 0],
                 [0, 0, 0]])

vacuum = VacuumCleanerAgent(room)
print("Initial room state:")
print(room)

# Start the vacuum cleaner operation
vacuum.operate()

print("Final room state:")
print(room)


Initial room state:
[[0 1 0]
 [1 1 0]
 [0 0 0]]
Cleaned spot at (1, 0). Total cleaned: 1


KeyboardInterrupt: 

**Explanation of the Code**

**Class Definition:**

The VacuumCleanerAgent class encapsulates the functionality of the vacuum cleaner.
The** __init__** method initializes the room (2D grid), the starting position, and the cleaned spots counter.
Methods:

**is_dirty**: Checks if the current position is dirty.

**clean**: Cleans the current position if it is dirty and updates the cleaned spots counter.

**move**: Moves the vacuum cleaner in a specified direction if possible.

**operate**: Implements the main cleaning logic. The vacuum cleaner will clean its current position and attempt to move to adjacent positions in a specified order (down, right, up, left).

**Example Usage:**

The room is represented as a 2D NumPy array where 1 indicates a dirty spot and 0 indicates a clean spot.
An instance of the vacuum cleaner agent is created, and the cleaning operation is initiated.
Running the Code
Copy and paste the entire code into a cell in your Google Colab notebook and run the cell.
The initial and final room states will be displayed, showing the cleaning process.
Additional Notes
You can modify the room configuration to test different scenarios (e.g., more dirty spots).
This simple implementation can be enhanced with more complex movement strategies or obstacle handling.

**Basic *italicized text* Weather Prediction Model**

Import Libraries:

In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


Create a Dataset: Simulate a small weather dataset:

In [18]:
data = {
    "Temperature": [30, 22, 35, 25, 28, 20, 18, 32, 40, 15],
    "Humidity": [70, 85, 60, 75, 80, 95, 90, 65, 50, 99],
    "Condition": ["Sunny", "Rainy", "Sunny", "Rainy", "Sunny", "Rainy", "Rainy", "Sunny", "Sunny", "Rainy"]
}

df = pd.DataFrame(data)


Prepare Features and Labels: Split the data into inputs (features) and outputs (labels):

In [19]:
X = df[["Temperature", "Humidity"]]
y = df["Condition"]


Split Data into Training and Testing Sets:

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


Train the Model: Use a Random Forest Classifier:

In [21]:
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

Test the Model: Evaluate its performance on the test data:

In [22]:
predictions = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, predictions))


Accuracy: 1.0


Make Predictions: Test with new input data:

In [28]:
new_weather = [[30, 55]]  # Example: 33°C and 55% humidity
print("Prediction:", model.predict(new_weather))


Prediction: ['Sunny']


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
